sudo: required
language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install .
  
script:
  - pytest --cov
  - cd tests
  - python -m unittest test_OrdinalEntroPy.TestEntropy

after_success:
  - bash <(curl -s https://codecov.io/bash)
